"""Public contracts for pure deal detection."""

from bot_ofertas.detection.engine import (
    COMMERCIAL_CONDITION_SIGNATURE_PREFIX,
    INFORMATIONAL_QUALITY_FLAGS,
    UNUSABLE_LIST_PRICE_QUALITY_FLAGS,
    ConfidenceLevel,
    DealClassification,
    DealDetector,
    DetectionDecision,
    DetectorConfig,
    ExpectedProductContext,
    PriceConditionFamily,
    QualityFlagAssessment,
    RejectionReason,
    SignalAssessment,
    SignalKind,
    SignalThresholds,
    assess_quality_flags,
    canonicalize_variant,
    commercial_condition_signatures,
    conditional_price_families,
    detect_deal,
)

__all__ = [
    "COMMERCIAL_CONDITION_SIGNATURE_PREFIX",
    "ConfidenceLevel",
    "DealClassification",
    "DealDetector",
    "DetectionDecision",
    "DetectorConfig",
    "ExpectedProductContext",
    "INFORMATIONAL_QUALITY_FLAGS",
    "PriceConditionFamily",
    "QualityFlagAssessment",
    "RejectionReason",
    "SignalAssessment",
    "SignalKind",
    "SignalThresholds",
    "UNUSABLE_LIST_PRICE_QUALITY_FLAGS",
    "assess_quality_flags",
    "canonicalize_variant",
    "commercial_condition_signatures",
    "conditional_price_families",
    "detect_deal",
]
