"""PostgreSQL persistence adapters."""

from bot_ofertas.storage.admin import (
    CrawlJobClaimBatch,
    CrawlJobEnqueueResult,
    CrawlJobRepository,
    IdempotencyConflictError,
    LeaseLostError,
    OptimisticConcurrencyError,
    RuntimePolicyRepository,
)
from bot_ofertas.storage.config import DatabaseSettings
from bot_ofertas.storage.database import (
    create_database_engine,
    create_session_factory,
    session_scope,
)
from bot_ofertas.storage.models import (
    AdminConfigRevision,
    Base,
    CrawlJob,
    CrawlJobItem,
    CrawlJobItemStatus,
    CrawlJobStatus,
    CrawlRun,
    CrawlRunStatus,
    DealDetection,
    NotificationDelivery,
    OfferAlertState,
    PriceObservationRecord,
    StoreCrawlState,
    TrackedProduct,
    WorkerCycleStatus,
    WorkerLifecycleStatus,
    WorkerRuntimeState,
    WorkerWatchdogState,
)
from bot_ofertas.storage.operations import (
    WatchdogAction,
    WatchdogDecision,
    WorkerAlreadyRunningError,
    WorkerOwnershipLostError,
    WorkerRuntimeStateRepository,
    WorkerWatchdogStateRepository,
)
from bot_ofertas.storage.repositories import (
    CrawlRunRepository,
    PriceObservationRepository,
    ProductClaimBatch,
    SaveObservationResult,
    StoreCrawlStateRepository,
    TrackedProductRepository,
)

__all__ = [
    "AdminConfigRevision",
    "Base",
    "CrawlJob",
    "CrawlJobClaimBatch",
    "CrawlJobEnqueueResult",
    "CrawlJobItem",
    "CrawlJobItemStatus",
    "CrawlJobRepository",
    "CrawlJobStatus",
    "CrawlRun",
    "CrawlRunRepository",
    "CrawlRunStatus",
    "DatabaseSettings",
    "DealDetection",
    "IdempotencyConflictError",
    "LeaseLostError",
    "NotificationDelivery",
    "OfferAlertState",
    "OptimisticConcurrencyError",
    "PriceObservationRecord",
    "PriceObservationRepository",
    "ProductClaimBatch",
    "SaveObservationResult",
    "StoreCrawlState",
    "StoreCrawlStateRepository",
    "TrackedProduct",
    "TrackedProductRepository",
    "RuntimePolicyRepository",
    "WatchdogAction",
    "WatchdogDecision",
    "WorkerAlreadyRunningError",
    "WorkerCycleStatus",
    "WorkerLifecycleStatus",
    "WorkerOwnershipLostError",
    "WorkerRuntimeState",
    "WorkerRuntimeStateRepository",
    "WorkerWatchdogState",
    "WorkerWatchdogStateRepository",
    "create_database_engine",
    "create_session_factory",
    "session_scope",
]
